name: Run code tests on push and pull requests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  push-tests:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Pixi (py314, ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          lfs: true
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          manifest-path: pyproject.toml
          environments: py314
          cache: false
          activate-environment: false
      - name: Lint
        run: pixi run lint
      - name: Run pytest
        run: pixi run -e py314 test

  pr-tests:
    if: github.event_name == 'pull_request'
    name: Pixi (${{ matrix.environment }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        environment: ["py313", "py314"]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          lfs: true
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          manifest-path: pyproject.toml
          environments: ${{ matrix.environment }}
          cache: false
          activate-environment: false
      - name: Run pytest
        run: pixi run -e ${{ matrix.environment }} test
